# server配置
server:
  port: 4000
  servlet:
    context-path: /

# 连接池配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://8.137.50.135:3306/aliPay?useSSL=false&serverTimezone=UTC
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
  springdoc:
    swagger-ui:
      path: /swagger-ui.html
  #jackson配置
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
# 开启debug日志
logging:
  level:
    root: info
# mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml

# mybatis-plus的配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.example.alipay.pojo
  global-config:
    db-config:
      logic-delete-field: isDeleted  #全局逻辑删除
      id-type: auto #主键策略自增长

